/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class EditSectorDialog extends javax.swing.JDialog {

    boolean okay;
    private int sector;
    
    public EditSectorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSector = new javax.swing.JLabel();
        tfSector = new javax.swing.JTextField();
        btOkay = new javax.swing.JButton();
        btCancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        lbSector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSector.setText("Sektor: ");
        getContentPane().add(lbSector);

        tfSector.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfSector);

        btOkay.setText("Bestätigen");
        btOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOkay(evt);
            }
        });
        getContentPane().add(btOkay);

        btCancle.setText("Abbrechen");
        btCancle.setToolTipText("");
        btCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancle(evt);
            }
        });
        getContentPane().add(btCancle);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Actionevent für den Button "Okay"
     * Die Eingabe wird auf Datentypen fehler überprüft, falls alles korrekt ist
     * wird okay auf true gesetzt und der Dialog geschlossen
     * @param evt 
     */
    private void onOkay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOkay
        try
        {
            sector = Integer.parseInt(tfSector.getText());
            if(sector < 0)
                throw new Exception("Ungültiger Sektor");
            okay = true;
            this.dispose();
        }
        catch(Exception e)
        {
            if(tfSector.getText().trim().isEmpty())
                this.dispose();
            else
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_onOkay

    /**
     * Actionevent für den Button "Cancle"
     * Der Dialog wird geschlossen.
     * @param evt 
     */
    private void onCancle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancle
        this.dispose();
    }//GEN-LAST:event_onCancle

    /**
     * Getter für okay
     * @return der Wert der Variable okay wird zurückgegebn
     */
    public boolean isOkay() {
        return okay;
    }

    /**
     * Getter für sector
     * @return der Wert der Variable sector wird zurückgegeben
     */
    public int getSector() {
        return sector;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancle;
    private javax.swing.JButton btOkay;
    private javax.swing.JLabel lbSector;
    private javax.swing.JTextField tfSector;
    // End of variables declaration//GEN-END:variables
}
