/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import parts.Foundation;
import data.Material;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class ModifyBarrierDialog extends javax.swing.JDialog
{
    
    private boolean okay = false;
    private double hohe;
    private double breite;
    private Material mat; 
    
    public ModifyBarrierDialog(java.awt.Frame parent, boolean modal, parts.Barrier lsw)
    {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        tfBreite.setText(""+lsw.getBreite());
        tfHohe.setText(""+lsw.getHoehe());
        
        for(data.Material mat : data.Material.values())
        {
            cbMaterial.addItem(mat);
        }
        
        if(lsw.getMat() != null)
            cbMaterial.setSelectedItem(lsw.getMat());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBreite = new javax.swing.JLabel();
        tfBreite = new javax.swing.JTextField();
        lbHohe = new javax.swing.JLabel();
        tfHohe = new javax.swing.JTextField();
        lbMaterial = new javax.swing.JLabel();
        cbMaterial = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        lbBreite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBreite.setText("Breite: ");
        getContentPane().add(lbBreite);
        getContentPane().add(tfBreite);

        lbHohe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHohe.setText("Höhe: ");
        getContentPane().add(lbHohe);
        getContentPane().add(tfHohe);

        lbMaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaterial.setText("Material: ");
        getContentPane().add(lbMaterial);

        getContentPane().add(cbMaterial);

        jButton1.setText("Bestätigen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOkay(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("Abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancle(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Actionevent für den Button "Okay", die Eingabe wird auf Datentypen Fehler
     * geprüft,falls alles korrekt ist wird okay auf true gesetzt und der Dialog
     * geschlossen
     * @param evt 
     */
    private void onOkay(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onOkay
    {//GEN-HEADEREND:event_onOkay
        
        try{
            hohe = Double.parseDouble(tfHohe.getText());
            breite = Double.parseDouble(tfBreite.getText());
            mat = (Material) cbMaterial.getSelectedItem();
            okay = true;
            this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_onOkay

    /**
     * Actionevent für den Button "Cancle"
     * Der dialog wird geschlossen.
     * @param evt 
     */
    private void onCancle(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onCancle
    {//GEN-HEADEREND:event_onCancle
        this.dispose();
    }//GEN-LAST:event_onCancle

    /**
     * getter für okay
     * @return der Wert der Variable okay wird zurückgegeben
     */
    public boolean isOkay()
    {
        return okay;
    }

    /**
     * Getter für hoehe
     * @return der Wert der Variable hohe wird zurückgegeben
     */
    public double getHohe()
    {
        return hohe;
    }

    /**
     * Getter für breite
     * @return  der Wert der Variable breite wird zurückgebeben
     */
    public double getBreite()
    {
        return breite;
    }

    /**
     * Getter für Material
     * @return der Wert der Variable mat wird zurückgegeben
     */
    public Material getMaterial()
    {
        return mat;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<data.Material> cbMaterial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbBreite;
    private javax.swing.JLabel lbHohe;
    private javax.swing.JLabel lbMaterial;
    private javax.swing.JTextField tfBreite;
    private javax.swing.JTextField tfHohe;
    // End of variables declaration//GEN-END:variables
}
